[2025-01-04T23:57:10.278+0000] {processor.py:153} INFO - Started process (PID=50) to work on /opt/airflow/dags/user_dag.py
[2025-01-04T23:57:10.279+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_dag.py for tasks to queue
[2025-01-04T23:57:10.279+0000] {logging_mixin.py:137} INFO - [2025-01-04T23:57:10.279+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_dag.py
[2025-01-04T23:57:10.334+0000] {logging_mixin.py:137} INFO - [2025-01-04T23:57:10.334+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_dag.py", line 5, in <module>
    from airflow.providers.http.operators.http import HttpOperator
ImportError: cannot import name 'HttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py)
[2025-01-04T23:57:10.335+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_dag.py
[2025-01-04T23:57:10.350+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_dag.py took 0.074 seconds
[2025-01-04T23:57:40.531+0000] {processor.py:153} INFO - Started process (PID=175) to work on /opt/airflow/dags/user_dag.py
[2025-01-04T23:57:40.532+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_dag.py for tasks to queue
[2025-01-04T23:57:40.532+0000] {logging_mixin.py:137} INFO - [2025-01-04T23:57:40.532+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_dag.py
[2025-01-04T23:57:40.550+0000] {logging_mixin.py:137} INFO - [2025-01-04T23:57:40.549+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_dag.py", line 5, in <module>
    from airflow.providers.http.operators.http import HttpOperator
ImportError: cannot import name 'HttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py)
[2025-01-04T23:57:40.550+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_dag.py
[2025-01-04T23:58:26.858+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_dag.py took 0.043 seconds
[2025-01-04T23:58:57.373+0000] {processor.py:153} INFO - Started process (PID=458) to work on /opt/airflow/dags/user_dag.py
[2025-01-04T23:58:57.376+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_dag.py for tasks to queue
[2025-01-04T23:58:57.376+0000] {logging_mixin.py:137} INFO - [2025-01-04T23:58:57.376+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_dag.py
[2025-01-04T23:58:57.403+0000] {logging_mixin.py:137} INFO - [2025-01-04T23:58:57.402+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_dag.py", line 5, in <module>
    from airflow.providers.http.operators.http import HttpOperator
ImportError: cannot import name 'HttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py)
[2025-01-04T23:58:57.403+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_dag.py
[2025-01-04T23:58:57.422+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_dag.py took 0.051 seconds
[2025-01-04T23:59:27.741+0000] {processor.py:153} INFO - Started process (PID=583) to work on /opt/airflow/dags/user_dag.py
[2025-01-04T23:59:27.742+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_dag.py for tasks to queue
[2025-01-04T23:59:27.742+0000] {logging_mixin.py:137} INFO - [2025-01-04T23:59:27.742+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_dag.py
[2025-01-04T23:59:27.762+0000] {logging_mixin.py:137} INFO - [2025-01-04T23:59:27.761+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_dag.py", line 5, in <module>
    from airflow.providers.http.operators.http import HttpOperator
ImportError: cannot import name 'HttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py)
[2025-01-04T23:59:27.762+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_dag.py
[2025-01-04T23:59:27.781+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_dag.py took 0.045 seconds
